app:
  name: "vortex_algorithms_synchronization"
  version: "1.0.0"

postgres:
  username: "postgres"
  host: "postgres"
  port: "5432"
  dbname: "postgres"
  sslmode: "disable"
  password: "qwerty"

http:
  port: 8000

log:
  level: "debug"

jwt:
  salt: "klwnrkmw;rlg[e'tk[]]"
  signing_key: "okojmtnknjehvdcutsychv;l/dgth"
  token_ttl: 12